version: '3'
services:
  iceval_web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
    env_file:
      - .env.prod
    restart: always
    ports:
      - "9003:9003"
    expose:
      - 8001
    command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - postgres
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - /home/prod/postgresql_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - iceval_web

  postgres:
    image: postgres:latest
    user: postgres # 指定普通用户
    env_file:
      - .env.prod
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - /home/prod/postgresql_data:/var/lib/postgresql/data



volumes:
  postgres_data:
