# Generated by Django 4.2.4 on 2023-11-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityinfo',
            name='charging_mode',
            field=models.CharField(default=1, max_length=20, verbose_name='充放电模式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energystorageinfo',
            name='installed_capacity',
            field=models.CharField(default=1, max_length=10, verbose_name='装机规模'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energystorageinfo',
            name='user_input',
            field=models.IntegerField(default=1, verbose_name='用户输入'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energystorageinfo',
            name='battery_capacity',
            field=models.CharField(max_length=10, verbose_name='储能系统电池容量'),
        ),
        migrations.AlterField(
            model_name='energystorageinfo',
            name='installed_units_num',
            field=models.IntegerField(verbose_name='选配台数'),
        ),
    ]
