# Generated by Django 4.2.4 on 2023-11-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0002_electricityinfo_charging_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricityinfo',
            name='charging_mode',
        ),
    ]
