# Generated by Django 4.2.4 on 2023-11-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0003_remove_electricityinfo_charging_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='energystorageinfo',
            name='charging_mode',
            field=models.CharField(default=1, max_length=10, verbose_name='充放电模式'),
            preserve_default=False,
        ),
    ]
