# Generated by Django 4.2.4 on 2023-11-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0004_energystorageinfo_charging_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energystorageinfo',
            name='battery_capacity',
            field=models.CharField(max_length=30, verbose_name='储能系统电池容量'),
        ),
        migrations.AlterField(
            model_name='energystorageinfo',
            name='charging_mode',
            field=models.CharField(max_length=20, verbose_name='充放电模式'),
        ),
        migrations.AlterField(
            model_name='energystorageinfo',
            name='installed_capacity',
            field=models.CharField(max_length=30, verbose_name='装机规模'),
        ),
    ]
