# Generated by Django 4.2.4 on 2023-11-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0005_alter_energystorageinfo_battery_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeEnergyStorageDisharingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10, verbose_name='用户id')),
                ('battery_attenuation_rate', models.CharField(max_length=10, verbose_name='电池衰减率')),
                ('year_operation_days', models.IntegerField(verbose_name='年运行天数')),
                ('month_operation_days', models.IntegerField(verbose_name='月运行天数')),
                ('unit_construction_cost', models.IntegerField(verbose_name='单位建设成本')),
                ('between_three_years', models.IntegerField(verbose_name='前三年单位运维成本')),
                ('three_years_before', models.IntegerField(verbose_name='三年后单位运维成本')),
                ('single_discharge', models.IntegerField(verbose_name='单台设备单次放电量')),
                ('single_charge', models.IntegerField(verbose_name='单台设备单次充电量')),
                ('project_total', models.IntegerField(verbose_name='项目总投资')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('all_compute_energy_storage', models.JSONField(verbose_name='计算储能信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '计算字段储能推荐充放电策略',
                'verbose_name_plural': '计算字段储能推荐充放电策略',
                'db_table': 'compute_energy_storage_disharing_info',
            },
        ),
        migrations.CreateModel(
            name='EnergyStorageDischaringInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_input', models.IntegerField(verbose_name='用户投入')),
                ('user_share_ratio', models.IntegerField(verbose_name='用户分成比例')),
                ('battery_capacity', models.CharField(max_length=30, verbose_name='储能系统电池容量')),
                ('charge_discharge_times', models.IntegerField(verbose_name='充放电次数')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('operation_duration', models.IntegerField(verbose_name='运行期限')),
                ('installed_capacity', models.CharField(max_length=30, verbose_name='装机规模')),
                ('installed_units_num', models.IntegerField(verbose_name='选配台数')),
                ('discharge_depth', models.IntegerField(verbose_name='放电深度')),
                ('charge_discharge_efficiency', models.IntegerField(verbose_name='充放电效率')),
                ('charging_mode', models.CharField(max_length=20, verbose_name='充放电模式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '储能推荐充放电策略',
                'verbose_name_plural': '储能推荐充放电策略',
                'db_table': 'energy_storage_discharing_info',
            },
        ),
        migrations.DeleteModel(
            name='EnergyStorageInfo',
        ),
    ]
