# Generated by Django 4.2.4 on 2023-11-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0006_computeenergystoragedisharinginfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energystoragedischaringinfo',
            name='user_id',
            field=models.CharField(default=1, max_length=10, verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
