# Generated by Django 4.2.4 on 2023-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0021_remove_electricityinfo_charge_discharge_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitevaluationinfo',
            name='project_npv',
            field=models.CharField(default=1, max_length=20, verbose_name='项目净现值'),
            preserve_default=False,
        ),
    ]
