# Generated by Django 4.2.4 on 2023-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iceval_app', '0024_alter_computeenergystoragedisharinginfo_between_three_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitevaluationinfo',
            name='status',
            field=models.CharField(default=1, max_length=20, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefitevaluationinfo',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='computeenergystoragedisharinginfo',
            name='battery_attenuation_rate',
            field=models.CharField(max_length=20, verbose_name='电池衰减率'),
        ),
        migrations.AlterField(
            model_name='computeenergystoragedisharinginfo',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='electricityinfo',
            name='cooperate_type',
            field=models.CharField(max_length=30, verbose_name='合作类型'),
        ),
        migrations.AlterField(
            model_name='electricityinfo',
            name='electric_type',
            field=models.CharField(max_length=50, verbose_name='用电类型'),
        ),
        migrations.AlterField(
            model_name='electricityinfo',
            name='power_curve_type',
            field=models.CharField(max_length=30, verbose_name='功率曲线类型'),
        ),
        migrations.AlterField(
            model_name='electricityinfo',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='electricityinfo',
            name='voltage_level',
            field=models.CharField(max_length=225, verbose_name='电压等级'),
        ),
        migrations.AlterField(
            model_name='electrictypeprice',
            name='electric_type',
            field=models.CharField(max_length=50, verbose_name='用电类型'),
        ),
        migrations.AlterField(
            model_name='electrictypeprice',
            name='region_id',
            field=models.CharField(max_length=50, verbose_name='省份id'),
        ),
        migrations.AlterField(
            model_name='energystoragedischaringinfo',
            name='cooperate_type',
            field=models.CharField(max_length=30, verbose_name='合作类型'),
        ),
        migrations.AlterField(
            model_name='energystoragedischaringinfo',
            name='user_id',
            field=models.CharField(max_length=30, verbose_name='用户id'),
        ),
    ]
